fix: only succeed if at least one commit status is successful

diff --git a/.github/workflows/_branch-head-commit-status-check.yml b/.github/workflows/_branch-head-commit-status-check.yml
--- a/.github/workflows/_branch-head-commit-status-check.yml
+++ b/.github/workflows/_branch-head-commit-status-check.yml
@@ -57,15 +57,13 @@ jobs:
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.branch }}/statuses")
 
-          FILTERED_STATUSES=$(echo "$STATUSES" | jq -r '.[] | select(.context | test("${{ inputs.check-status-context-pattern }}"))')
-          echo "Filtered Statuses: $FILTERED_STATUSES"
           FILTERED_STATUSES=$(echo "$STATUSES" | jq -r '.[] | select(.context | test("${{ inputs.check-status-context-pattern }}")) | .state')
 
-          # Check if any filtered status is pending or failure
-          if echo "$FILTERED_STATUSES" | grep -qE "pending|failure"; then
-            echo "Failing the workflow as a commit status on ${{ inputs.branch }} is pending or failure."
-            exit 1
-          else
-            echo "Succeeding the workflow. All filtered commit statuses on ${{ inputs.branch }} are successful."
+          # Check if any filtered status is success
+          if echo "$FILTERED_STATUSES" | grep -q "success"; then
+            echo "Succeeding the workflow. At least one filtered commit status on ${{ inputs.branch }} is successful."
             exit 0
+          else
+            echo "Failing the workflow as no commit status on ${{ inputs.branch }} matching the pattern is successful."
+            exit 1
           fi
